### PR TITLE
Update to React 15

### PR DESCRIPTION
**Pull request by bestan**

### CODE REVIEW

**Comment by fluse** [comment]
increase version to 15.02 pls

**Comment by bestan** [comment]
@fluse here you go 😄

**Comment by fluse** [comment]
@Pomax are you alive?

**Comment by Pomax** [comment]
Me? yes. Github? Not so much. Without an @mention, even though this is my repo and I'm set to watch it, github notifies me of jack shit. Thanks for the ping, I'll merge this in.

**Comment by Pomax** [comment]
v2.0.0 published (major version because of compatibility breaking changes)

**Pull request merged**
